-- Seed from Wikipedia's List of American Plays + commonly produced international works
-- ON CONFLICT (slug) DO NOTHING — safe to re-run, won't duplicate existing 177 plays

INSERT INTO plays (title, slug, playwright, year_written, awards, synopsis) VALUES
-- Commonly produced American plays not yet in catalog
('Arsenic and Old Lace', 'arsenic-and-old-lace', 'Joseph Kesselring', 1939, '{}', 'Two sweet old ladies poison lonely gentlemen with elderberry wine while their nephew tries to keep the family secret.'),
('Barefoot in the Park', 'barefoot-in-the-park', 'Neil Simon', 1963, '{}', 'Newlyweds in a cramped fifth-floor walkup discover that love alone doesn''t pay the heating bill.'),
('Born Yesterday', 'born-yesterday', 'Garson Kanin', 1946, '{}', 'A corrupt tycoon hires a journalist to educate his showgirl girlfriend, who turns out to be smarter than everyone.'),
('The Boys in the Band', 'the-boys-in-the-band', 'Mart Crowley', 1968, '{}', 'A birthday party among gay friends in 1960s New York turns vicious when a straight college friend drops in.'),
('Brighton Beach Memoirs', 'brighton-beach-memoirs', 'Neil Simon', 1982, '{}', 'A teenager in 1937 Brooklyn navigates puberty, poverty, and a house with too many relatives.'),
('Bus Stop', 'bus-stop', 'William Inge', 1955, '{}', 'A cowboy kidnaps a nightclub singer during a snowstorm and a group of strangers wait out the night at a Kansas bus stop.'),
('Come Back, Little Sheba', 'come-back-little-sheba', 'William Inge', 1950, '{}', 'A recovering alcoholic and his disappointed wife take in a young boarder who reopens old wounds.'),
('Desire Under the Elms', 'desire-under-the-elms', 'Eugene O''Neill', 1924, '{}', 'A young bride, an old farmer, and his son form a triangle of desire and violence on a New England farm.'),
('The Elephant Man', 'the-elephant-man', 'Bernard Pomerance', 1977, '{}', 'A Victorian doctor takes in Joseph Merrick, severely deformed and exhibited as a sideshow freak, and gives him dignity.'),
('A Few Good Men', 'a-few-good-men', 'Aaron Sorkin', 1989, '{}', 'A Navy lawyer defends two Marines accused of murder at Guantanamo Bay and uncovers a culture of abuse.'),
('The Front Page', 'the-front-page', 'Ben Hecht & Charles MacArthur', 1928, '{}', 'A reporter tries to quit the newspaper business on the eve of a sensational execution, but his editor won''t let him go.'),
('Harvey', 'harvey', 'Mary Chase', 1944, ARRAY['Pulitzer Prize for Drama, 1945'], 'A kind, eccentric man''s best friend is a six-foot-tall invisible rabbit, and his family wants him committed.'),
('The Iceman Cometh', 'the-iceman-cometh', 'Eugene O''Neill', 1939, '{}', 'A traveling salesman arrives at a waterfront bar to liberate his drinking companions from their pipe dreams.'),
('Lady Day at Emerson''s Bar and Grill', 'lady-day-at-emersons-bar-and-grill', 'Lanie Robertson', 1986, '{}', 'Billie Holiday performs one of her final concerts in a Philadelphia bar, unraveling between songs.'),
('Lobby Hero', 'lobby-hero', 'Kenneth Lonergan', 2001, '{}', 'A night security guard in a Manhattan apartment building stumbles into a moral crisis involving a cop and his partner.'),
('Lost in Yonkers', 'lost-in-yonkers', 'Neil Simon', 1990, ARRAY['Pulitzer Prize for Drama, 1991'], 'Two boys spend a summer with their harsh grandmother and childlike aunt in wartime Yonkers.'),
('Love! Valour! Compassion!', 'love-valour-compassion', 'Terrence McNally', 1994, ARRAY['Tony Award for Best Play, 1995'], 'Eight gay men spend three summer weekends at a country house, navigating love, jealousy, and AIDS.'),
('Master Class', 'master-class', 'Terrence McNally', 1995, ARRAY['Tony Award for Best Play, 1996'], 'Maria Callas teaches a master class at Juilliard, terrorizing her students while reliving her own triumphs.'),
('The Odd Couple', 'the-odd-couple', 'Neil Simon', 1965, '{}', 'A neat freak and a slob try to share an apartment after their marriages fall apart.'),
('On Golden Pond', 'on-golden-pond', 'Ernest Thompson', 1979, '{}', 'An elderly couple spends what may be their last summer at their lake house, confronting mortality and family.'),
('Our Town', 'our-town-wilder', 'Thornton Wilder', 1938, ARRAY['Pulitzer Prize for Drama, 1938'], 'A Stage Manager narrates daily life, love, and death in the small town of Grover''s Corners.'),
('Picnic', 'picnic', 'William Inge', 1953, ARRAY['Pulitzer Prize for Drama, 1953'], 'A drifter arrives in a small Kansas town on Labor Day and upends the lives of every woman he meets.'),
('The Subject Was Roses', 'the-subject-was-roses', 'Frank D. Gilroy', 1964, ARRAY['Pulitzer Prize for Drama, 1965'], 'A soldier returns from WWII to find his parents'' marriage worse than he remembered.'),
('That Championship Season', 'that-championship-season', 'Jason Miller', 1972, ARRAY['Pulitzer Prize for Drama, 1973'], 'Four members of a championship basketball team reunite with their coach twenty years later and the lies surface.'),
('This Is Our Youth', 'this-is-our-youth', 'Kenneth Lonergan', 1996, '{}', 'Two privileged Upper West Side burnouts steal money from a drug-dealing father and try to impress a girl.'),
('Torch Song Trilogy', 'torch-song-trilogy', 'Harvey Fierstein', 1982, ARRAY['Tony Award for Best Play, 1983'], 'A drag performer in New York searches for love, respect, and family across three decades.'),
('The Trip to Bountiful', 'the-trip-to-bountiful', 'Horton Foote', 1953, '{}', 'An elderly woman escapes her Houston apartment to visit her childhood home in rural Texas one last time.'),
('Vanya and Sonia and Masha and Spike', 'vanya-and-sonia-and-masha-and-spike', 'Christopher Durang', 2012, ARRAY['Tony Award for Best Play, 2013'], 'Three middle-aged siblings in Bucks County fight about their wasted lives when the famous one comes home with her boy toy.'),
('You Can''t Take It with You', 'you-cant-take-it-with-you', 'George S. Kaufman & Moss Hart', 1936, ARRAY['Pulitzer Prize for Drama, 1937'], 'A gloriously eccentric family does whatever makes them happy, to the horror of the neighbors.'),
('To Kill a Mockingbird', 'to-kill-a-mockingbird', 'Aaron Sorkin', 2018, '{}', 'Atticus Finch defends a Black man falsely accused of rape in Depression-era Alabama.'),
('The Waverly Gallery', 'the-waverly-gallery', 'Kenneth Lonergan', 2000, '{}', 'A grandmother''s dementia slowly erases her identity as her family watches from an art gallery in Greenwich Village.'),
('One Night in Miami', 'one-night-in-miami', 'Kemp Powers', 2013, '{}', 'Muhammad Ali, Malcolm X, Sam Cooke, and Jim Brown meet in a Miami hotel room after the 1964 heavyweight fight.'),
('The Flick', 'the-flick', 'Annie Baker', 2013, ARRAY['Pulitzer Prize for Drama, 2014'], 'Three underpaid movie theater employees sweep popcorn and fall in love in real time.'),
('John', 'john', 'Annie Baker', 2015, '{}', 'A couple checks into a B&B in Gettysburg and the innkeeper may or may not be haunted.'),
('The Antipodes', 'the-antipodes', 'Annie Baker', 2017, '{}', 'A group of people sit in a conference room trying to come up with the perfect story.'),
('School Girls; Or, the African Mean Girls Play', 'school-girls-african-mean-girls', 'Jocelyn Bioh', 2017, '{}', 'A queen bee at a Ghanaian boarding school is threatened when a new student arrives who might win Miss Ghana.'),
('POTUS', 'potus', 'Selina Fillinger', 2022, '{}', 'Seven women scramble to contain a crisis caused by the President''s unguarded remark.'),
('Peter and the Starcatcher', 'peter-and-the-starcatcher', 'Rick Elice', 2009, '{}', 'The origin story of Peter Pan, told by a dozen actors with trunks, ropes, and a lot of imagination.'),
('The Humans', 'the-humans-karam', 'Stephen Karam', 2015, ARRAY['Tony Award for Best Play, 2016'], 'The Blake family gathers for Thanksgiving in a crumbling Chinatown duplex.'),
('Frankie and Johnny in the Clair de Lune', 'frankie-and-johnny', 'Terrence McNally', 1982, '{}', 'A short-order cook and a waitress spend the night together and argue about whether this could be love.'),
('Awake and Sing!', 'awake-and-sing', 'Clifford Odets', 1935, '{}', 'A Jewish family in the Bronx during the Depression dreams of escape while the grandfather reads Marx.'),
('The Man Who Came to Dinner', 'the-man-who-came-to-dinner', 'George S. Kaufman & Moss Hart', 1939, '{}', 'A famous critic breaks his hip at dinner and tyrannizes his hosts'' home for weeks.'),
('Dinner at Eight', 'dinner-at-eight', 'Edna Ferber & George S. Kaufman', 1932, '{}', 'A society hostess plans an elegant dinner party while each guest''s life falls apart.'),
('Stage Door', 'stage-door', 'Edna Ferber & George S. Kaufman', 1936, '{}', 'Aspiring actresses in a New York boarding house compete for parts and survive on dreams.'),
('Mourning Becomes Electra', 'mourning-becomes-electra', 'Eugene O''Neill', 1931, '{}', 'The Oresteia transplanted to Civil War New England — murder, adultery, and vengeance across three plays.'),
('Anna Christie', 'anna-christie', 'Eugene O''Neill', 1921, ARRAY['Pulitzer Prize for Drama, 1922'], 'A sailor''s daughter returns from a hard life to find her father on a coal barge and falls for a stoker.'),
('Beyond the Horizon', 'beyond-the-horizon', 'Eugene O''Neill', 1918, ARRAY['Pulitzer Prize for Drama, 1920'], 'Two brothers love the same woman; the wrong one stays home and the wrong one goes to sea.'),
('Street Scene', 'street-scene', 'Elmer Rice', 1929, ARRAY['Pulitzer Prize for Drama, 1929'], 'Twenty-four hours on the stoop of a New York tenement, ending in murder.'),
('The Adding Machine', 'the-adding-machine', 'Elmer Rice', 1923, '{}', 'A bookkeeper is replaced by a machine, kills his boss, and navigates an expressionist afterlife.'),
('Biloxi Blues', 'biloxi-blues', 'Neil Simon', 1984, ARRAY['Tony Award for Best Play, 1985'], 'A young writer endures Army basic training in Mississippi during World War II.'),
('The Sunshine Boys', 'the-sunshine-boys', 'Neil Simon', 1972, '{}', 'Two aging vaudevillians who hate each other are reunited for a TV special.'),
('Plaza Suite', 'plaza-suite', 'Neil Simon', 1968, '{}', 'Three couples occupy the same suite at the Plaza Hotel in three acts of comedy.'),
('Abe Lincoln in Illinois', 'abe-lincoln-in-illinois', 'Robert E. Sherwood', 1938, ARRAY['Pulitzer Prize for Drama, 1939'], 'Lincoln''s life from log cabin to the White House steps, struggling with ambition and depression.'),
('Gary: A Sequel to Titus Andronicus', 'gary-a-sequel-to-titus-andronicus', 'Taylor Mac', 2019, '{}', 'Two servants clean up the corpses after Shakespeare''s bloodiest tragedy and argue about the future of civilization.'),
('Corpus Christi', 'corpus-christi', 'Terrence McNally', 1998, '{}', 'The story of Jesus reimagined as a gay man in modern-day Corpus Christi, Texas.'),
('Lips Together, Teeth Apart', 'lips-together-teeth-apart', 'Terrence McNally', 1991, '{}', 'Two straight couples spend Fourth of July in a Fire Island beach house inherited from a friend who died of AIDS.')
ON CONFLICT (slug) DO NOTHING;
