-- Art Classes Discovery: seed 8 canonical Chicago art education venues
INSERT INTO public.venues (name, slug, description, venue_type, address, neighborhood, city, latitude, longitude, website_url, calendar_url, price_range, genre_tags, source)
VALUES
  (
    'The Second City Training Center',
    'second-city-training',
    'The world-famous comedy and improv conservatory. Programs range from beginner drop-ins to the full conservatory track.',
    'school',
    '1616 N Wells St, Chicago, IL 60614',
    'Old Town',
    'chicago',
    41.9132, -87.6362,
    'https://www.secondcity.com/training/',
    'https://www.secondcity.com/chicago/training/schedule/',
    '$$',
    ARRAY['improv', 'comedy', 'sketch'],
    'manual'
  ),
  (
    'iO Chicago',
    'io-chicago',
    'The home of long-form improv. Offers classes from Harold basics through advanced ensemble training.',
    'school',
    '1501 N Kingsbury St, Chicago, IL 60642',
    'Lincoln Park',
    'chicago',
    41.9077, -87.6401,
    'https://ioimprov.com/',
    'https://ioimprov.com/chicago/classes/',
    '$$',
    ARRAY['improv', 'long-form'],
    'manual'
  ),
  (
    'The Annoyance Theatre & Bar',
    'annoyance-theatre',
    'Chicago''s irreverent home for avant-garde comedy and improv. Classes focus on character-based work and devised performance.',
    'school',
    '851 W Belmont Ave, Chicago, IL 60657',
    'Lakeview',
    'chicago',
    41.9394, -87.6501,
    'https://theannoyance.com/',
    'https://theannoyance.com/classes/',
    '$',
    ARRAY['improv', 'comedy', 'experimental'],
    'manual'
  ),
  (
    'Chicago Improv Studio',
    'chicago-improv-studio',
    'Founded by veteran iO instructors. Smaller class sizes and a curriculum built around the Harold form.',
    'school',
    '3541 N Clark St, Chicago, IL 60657',
    'Wrigleyville',
    'chicago',
    41.9497, -87.6555,
    'https://chicagoimprovstudio.com/',
    'https://chicagoimprovstudio.com/classes/',
    '$',
    ARRAY['improv', 'comedy'],
    'manual'
  ),
  (
    'Acting Studio Chicago',
    'acting-studio-chicago',
    'Meisner-based acting training for adults. Programs span scene study, audition technique, and on-camera work.',
    'school',
    '5955 N Broadway, Chicago, IL 60660',
    'Edgewater',
    'chicago',
    41.9899, -87.6600,
    'https://actingstudiochicago.com/',
    'https://actingstudiochicago.com/classes/',
    '$$',
    ARRAY['acting', 'meisner', 'scene-study'],
    'manual'
  ),
  (
    'Piven Theatre Workshop',
    'piven-theatre-workshop',
    'Story Theater and ensemble training rooted in the Piven tradition. Adult programs in improvisation, storytelling, and performance.',
    'school',
    '927 Noyes St, Evanston, IL 60201',
    'Evanston',
    'chicago',
    42.0594, -87.6827,
    'https://piventheatre.org/',
    'https://piventheatre.org/classes/',
    '$$',
    ARRAY['story-theater', 'improvisation', 'ensemble'],
    'manual'
  ),
  (
    'Old Town School of Folk Music',
    'old-town-school',
    'Community arts institution. Theater and performance classes alongside music — including storytelling, puppetry, and musical theater.',
    'school',
    '4544 N Lincoln Ave, Chicago, IL 60625',
    'Lincoln Square',
    'chicago',
    41.9672, -87.6857,
    'https://www.oldtownschool.org/',
    'https://www.oldtownschool.org/classes/?category=theater',
    '$',
    ARRAY['storytelling', 'musical-theater', 'community'],
    'manual'
  ),
  (
    'Steppenwolf Theatre — Education',
    'steppenwolf-education',
    'Steppenwolf''s education division. Adult acting intensives and scene study workshops led by ensemble members.',
    'school',
    '1650 N Halsted St, Chicago, IL 60614',
    'Lincoln Park',
    'chicago',
    41.9126, -87.6482,
    'https://www.steppenwolf.org/education/',
    'https://www.steppenwolf.org/education/adult-programs/',
    '$$$',
    ARRAY['acting', 'scene-study', 'ensemble'],
    'manual'
  )
ON CONFLICT (slug) DO NOTHING;
